-- Update events to set is_special flag appropriately
UPDATE events SET is_special = 0 WHERE title IN (
  'R&B PARTY',
  'V5 REGGAETON NIGHTS', 
  'WOMENS EMPOWERMENT EVENT',
  'RANCHO Y GALOPE',
  'THE NEW YORK MARIACHI SPECTACULAR',
  'JESSI URIBE EN CONCIERTO',
  'SEGUNDO ROSERO & FRANCIS',
  'PERREO EN EXCESO! RANDY & DJ ADONII',
  'COSCULLUELA USA TOUR 2025',
  'CHARLIE ZAA EXCLUSIVO UNICA PRESENTACIÓN'
);

-- Set some premium events as special
UPDATE events SET is_special = 1 WHERE title IN (
  'THE NEW YORK MARIACHI SPECTACULAR',
  'CHARLIE ZAA EXCLUSIVO UNICA PRESENTACIÓN',
  'COSCULLUELA USA TOUR 2025'
);